// src/common/constants/error-codes.constants.ts
export const ERROR_CODES = {
  // Autenticación (AUTH_*)
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INCORRECT_PASSWORD: 'AUTH_INCORRECT_PASSWORD',
  AUTH_DUPLICATE_EMAIL: 'AUTH_DUPLICATE_EMAIL',
  AUTH_DUPLICATE_USERNAME: 'AUTH_DUPLICATE_USERNAME',
  AUTH_EMAIL_NOT_CONFIRMED: 'AUTH_EMAIL_NOT_CONFIRMED',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_INVALID_HASH: 'AUTH_INVALID_HASH',
  AUTH_MISSING_OLD_PASSWORD: 'AUTH_MISSING_OLD_PASSWORD',
  AUTH_INCORRECT_OLD_PASSWORD: 'AUTH_INCORRECT_OLD_PASSWORD',
  AUTH_SESSION_EXPIRED_OR_INVALID: 'AUTH_SESSION_EXPIRED_OR_INVALID', // Para refresh token
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED', // Error genérico 401
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN', // Error genérico 403 (roles)

  // Validación (VALIDATION_*)
  VALIDATION_ERROR: 'VALIDATION_ERROR', // Error genérico para class-validator

  // Recursos (RESOURCE_*)
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND', // Error genérico 404
  AREA_NOT_FOUND: 'AREA_NOT_FOUND',
  TABLE_NOT_FOUND: 'TABLE_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  SUBCATEGORY_NOT_FOUND: 'SUBCATEGORY_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_VARIANT_NOT_FOUND: 'PRODUCT_VARIANT_NOT_FOUND',
  MODIFIER_GROUP_NOT_FOUND: 'MODIFIER_GROUP_NOT_FOUND',
  PRODUCT_MODIFIER_NOT_FOUND: 'PRODUCT_MODIFIER_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ITEM_NOT_FOUND: 'ORDER_ITEM_NOT_FOUND',
  ORDER_ITEM_MODIFIER_NOT_FOUND: 'ORDER_ITEM_MODIFIER_NOT_FOUND',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  PREPARATION_SCREEN_NOT_FOUND: 'PREPARATION_SCREEN_NOT_FOUND',
  // ... otros recursos

  // Conflictos (CONFLICT_*)
  CONFLICT_ERROR: 'CONFLICT_ERROR', // Error genérico 409
  AREA_NAME_EXISTS: 'AREA_NAME_EXISTS',
  // ... otros conflictos específicos
  THERMAL_PRINTER_DUPLICATE_FIELD: 'THERMAL_PRINTER_DUPLICATE_FIELD',

  // Errores del Servidor (SERVER_*)
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR', // Error genérico 500
  DATABASE_ERROR: 'DATABASE_ERROR',
  MAIL_SEND_ERROR: 'MAIL_SEND_ERROR',
  FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',

  // Otros
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
