// src/common/tokens.ts
export const SESSION_REPOSITORY = Symbol('SESSION_REPOSITORY');
export const AREA_REPOSITORY = Symbol('AREA_REPOSITORY');
export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY');
export const SUBCATEGORY_REPOSITORY = Symbol('SUBCATEGORY_REPOSITORY');
export const PRODUCT_REPOSITORY = Symbol('PRODUCT_REPOSITORY');
export const PRODUCT_MODIFIER_REPOSITORY = Symbol('PRODUCT_MODIFIER_REPOSITORY');
export const PAYMENT_REPOSITORY = Symbol('PAYMENT_REPOSITORY');
export const PREPARATION_SCREEN_REPOSITORY = Symbol('PREPARATION_SCREEN_REPOSITORY');
export const PRODUCT_vARIANT_REPOSITORY = Symbol('PRODUCT_VARIANT_REPOSITORY');
export const TABLE_REPOSITORY = Symbol('TABLE_REPOSITORY');
export const CUSTOMER_REPOSITORY = Symbol('CUSTOMER_REPOSITORY');
export const ADDRESS_REPOSITORY = Symbol('ADDRESS_REPOSITORY');
export const FILE_REPOSITORY = Symbol('FILE_REPOSITORY');
export const MODIFIER_GROUP_REPOSITORY = Symbol('MODIFIER_GROUP_REPOSITORY');
export const PRODUCT_VARIANT_REPOSITORY = Symbol('PRODUCT_VARIANT_REPOSITORY');
export const THERMAL_PRINTER_REPOSITORY = Symbol('THERMAL_PRINTER_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');

// Orders Module Tokens
export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');
export const DAILY_ORDER_COUNTER_REPOSITORY = Symbol('DAILY_ORDER_COUNTER_REPOSITORY');
export const ORDER_ITEM_REPOSITORY = Symbol('ORDER_ITEM_REPOSITORY');
export const ORDER_ITEM_MODIFIER_REPOSITORY = Symbol('ORDER_ITEM_MODIFIER_REPOSITORY');
export const TICKET_IMPRESSION_REPOSITORY = Symbol('TICKET_IMPRESSION_REPOSITORY');
export const ORDER_HISTORY_REPOSITORY = Symbol('ORDER_HISTORY_REPOSITORY');
export const ORDER_ITEM_HISTORY_REPOSITORY = Symbol('ORDER_ITEM_HISTORY_REPOSITORY');
